version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cold_email
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
